# Generated by Django 4.2 on 2026-06-11 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='refund_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='refund_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='refund_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='refund_payment_mode',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='RefundReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50, unique=True)),
                ('receipt_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque')], default='CASH', max_length=15)),
                ('cheque_no', models.CharField(blank=True, max_length=100)),
                ('cheque_bank', models.CharField(blank=True, max_length=200)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('narration', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancellation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_receipt', to='sales.cancellation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
