# Generated by Django 4.2 on 2026-06-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_cancellation_refund_notes_cancellation_refund_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='inteqal_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='possession',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='registry_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
