# Generated by Django 5.2.15 on 2026-06-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_booking_inteqal_no_booking_possession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="possession_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="bookings/possession/"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="registry_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="bookings/registry/"
            ),
        ),
    ]
