# Generated by Django 4.2 on 2026-06-07 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_urdu', models.CharField(blank=True, max_length=100)),
                ('total_plots', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.CharField(max_length=50)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_unit', models.CharField(choices=[('MARLA', 'Marla'), ('KANAL', 'Kanal'), ('SQFT', 'Square Feet')], default='MARLA', max_length=10)),
                ('plot_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('CORNER', 'Corner')], default='RESIDENTIAL', max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('HOLD', 'Hold'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='development.block')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['block', 'plot_no'],
                'unique_together': {('block', 'plot_no')},
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_urdu', models.CharField(blank=True, max_length=200)),
                ('location', models.TextField(blank=True)),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('land_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='towns', to='land.landcontract')),
            ],
        ),
        migrations.CreateModel(
            name='TownMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Master Plan, Block A Layout', max_length=200)),
                ('map_type', models.CharField(choices=[('IMAGE', 'Image (JPG/PNG)'), ('PDF', 'PDF')], default='IMAGE', max_length=10)),
                ('map_file', models.FileField(upload_to='maps/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='development.block')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps_created', to=settings.AUTH_USER_MODEL)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='development.town')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='development.town'),
        ),
        migrations.CreateModel(
            name='PlotCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinates_created', to=settings.AUTH_USER_MODEL)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='development.plot')),
                ('town_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='development.townmap')),
            ],
            options={
                'unique_together': {('town_map', 'plot')},
            },
        ),
    ]
