# Generated by Django 4.2 on 2026-06-11 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expense_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque')], default='CASH', max_length=10)),
                ('paid_to', models.CharField(blank=True, max_length=200)),
                ('cheque_no', models.CharField(blank=True, max_length=50)),
                ('cheque_bank', models.CharField(blank=True, max_length=100)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('narration', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='expenses/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
